# Generated by Django 4.2.8 on 2025-11-28 06:39

from django.db import migrations, models


def update_usernames_to_emails(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        user.username = user.email
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RunPython(update_usernames_to_emails),
    ]
