# Generated by Django 4.2.8 on 2025-11-21 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback pour cette réponse')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('quiz', 'Quiz'), ('coding', 'Code'), ('matching', 'Appariement'), ('essay', 'Essai'), ('fill_blank', 'Compléter'), ('multiple_choice', 'Choix multiples')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=20)),
                ('instructions', models.TextField()),
                ('points', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('learning_objectives', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('adaptive', models.BooleanField(default=False, help_text='Exercice adaptatif par IA')),
                ('adjust_difficulty', models.BooleanField(default=False, help_text='Ajuster la difficulté automatiquement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='content.lesson')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['lesson', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('submitted', 'Soumis'), ('graded', 'Évalué'), ('reviewed', 'Revu')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField()),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True, help_text='Feedback généré par IA')),
                ('attempts_count', models.IntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Soumission d'exercice",
                'verbose_name_plural': "Soumissions d'exercice",
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Choix multiples'), ('true_false', 'Vrai/Faux'), ('short_answer', 'Réponse courte'), ('essay', 'Essai'), ('coding', 'Code'), ('fill_blank', 'Compléter'), ('matching', 'Appariement')], max_length=50)),
                ('order', models.IntegerField()),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Explication de la réponse correcte')),
                ('image', models.ImageField(blank=True, upload_to='questions/')),
                ('hints', models.JSONField(default=list)),
                ('difficulty_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['exercise', 'order'],
                'unique_together': {('exercise', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pass_percentage', models.FloatField(default=70.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('randomize_questions', models.BooleanField(default=False)),
                ('randomize_answers', models.BooleanField(default=False)),
                ('shuffle_mode', models.BooleanField(default=False)),
                ('show_answers', models.BooleanField(default=True)),
                ('allow_review', models.BooleanField(default=True)),
                ('max_attempts', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.lesson')),
                ('questions', models.ManyToManyField(to='exercises.question')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_response', models.TextField(blank=True)),
                ('code_response', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('attempt_number', models.IntegerField(default=1)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.question')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.answer')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='exercises.exercisesubmission')),
            ],
            options={
                'verbose_name': 'Réponse à une question',
                'verbose_name_plural': 'Réponses aux questions',
                'ordering': ['submission', 'question__order'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exercises.question'),
        ),
        migrations.AddIndex(
            model_name='exercisesubmission',
            index=models.Index(fields=['user', 'exercise'], name='exercises_e_user_id_515181_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesubmission',
            index=models.Index(fields=['status'], name='exercises_e_status_6e31d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'order')},
        ),
    ]
