# Generated by Django 4.2.8 on 2025-11-21 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Code unique pour le template', max_length=100, unique=True)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField()),
                ('available_variables', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Email',
                'verbose_name_plural': 'Templates Email',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reminder', 'Rappel'), ('achievement', 'Accomplissement'), ('recommendation', 'Recommandation'), ('message', 'Message'), ('alert', 'Alerte'), ('encouragement', 'Encouragement'), ('milestone', 'Jalon'), ('course_update', 'Mise à jour cours')], max_length=50)),
                ('channel', models.CharField(choices=[('in_app', "Dans l'application"), ('email', 'Email'), ('push', 'Notification Push'), ('sms', 'SMS')], default='in_app', max_length=50)),
                ('priority', models.IntegerField(default=0, help_text='Priorité (0-10)')),
                ('personalized', models.BooleanField(default=True, help_text='Adaptée au profil')),
                ('emotional_state_aware', models.BooleanField(default=False, help_text="Adaptée à l'état émotionnel")),
                ('related_content', models.CharField(blank=True, help_text='JSON de contenu lié', max_length=500)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reminder', 'Rappel'), ('achievement', 'Accomplissement'), ('recommendation', 'Recommandation'), ('message', 'Message'), ('alert', 'Alerte'), ('encouragement', 'Encouragement'), ('milestone', 'Jalon'), ('course_update', 'Mise à jour cours')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('custom', 'Personnalisé')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(help_text="Heure d'envoi (HH:MM)")),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programmation de notification',
                'verbose_name_plural': 'Programmations de notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_email', models.BooleanField(default=True)),
                ('enable_push', models.BooleanField(default=True)),
                ('enable_in_app', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('enable_reminders', models.BooleanField(default=True)),
                ('enable_achievements', models.BooleanField(default=True)),
                ('enable_recommendations', models.BooleanField(default=True)),
                ('enable_messages', models.BooleanField(default=True)),
                ('enable_alerts', models.BooleanField(default=True)),
                ('enable_encouragement', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='HH:MM', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='HH:MM', null=True)),
                ('email_frequency', models.CharField(choices=[('instant', 'Immédiat'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('never', 'Jamais')], default='daily', max_length=20)),
                ('allow_personalization', models.BooleanField(default=True)),
                ('allow_emotional_adaptation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', "Dans l'application"), ('email', 'Email'), ('push', 'Notification Push'), ('sms', 'SMS')], max_length=50)),
                ('recipient', models.CharField(help_text='Email ou téléphone', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('failed', 'Échoué'), ('bounced', 'Rejeté'), ('unsubscribed', 'Désinscrit')], max_length=50)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Journal de notification',
                'verbose_name_plural': 'Journaux de notification',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'),
        ),
    ]
