# Generated by Django 4.2.8 on 2025-11-21 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_learning_time', models.IntegerField(default=0, help_text='Temps total en minutes')),
                ('total_courses_enrolled', models.IntegerField(default=0)),
                ('total_courses_completed', models.IntegerField(default=0)),
                ('total_exercises_attempted', models.IntegerField(default=0)),
                ('total_exercises_passed', models.IntegerField(default=0)),
                ('average_exercise_score', models.FloatField(default=0.0)),
                ('average_course_completion_time', models.IntegerField(default=0)),
                ('average_daily_learning_time', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('learning_consistency', models.FloatField(default=0.0, help_text='Score de cohérence (0-100)')),
                ('motivation_level', models.FloatField(default=50.0, help_text='Niveau de motivation estimé (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytique utilisateur',
                'verbose_name_plural': 'Analytiques utilisateur',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('total_duration_hours', models.FloatField()),
                ('difficulty_progression', models.JSONField(default=list, help_text='Liste des difficultés')),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='paths', to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Parcours d'apprentissage",
                'verbose_name_plural': "Parcours d'apprentissage",
            },
        ),
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('average_time_spent', models.IntegerField(default=0)),
                ('avg_exercises_per_user', models.FloatField(default=0.0)),
                ('dropout_rate', models.FloatField(default=0.0)),
                ('most_challenging_modules', models.JSONField(default=list)),
                ('user_feedback_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='content.course')),
            ],
            options={
                'verbose_name': 'Analytique cours',
                'verbose_name_plural': 'Analytiques cours',
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('total_attempts', models.IntegerField(default=0)),
                ('successful_attempts', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('time_trend', models.JSONField(default=list, help_text='Progression temporelle')),
                ('difficulty_rating', models.FloatField(default=0.0)),
                ('last_attempted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrique de performance',
                'verbose_name_plural': 'Métriques de performance',
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('learning_time_minutes', models.IntegerField(default=0)),
                ('exercises_attempted', models.IntegerField(default=0)),
                ('exercises_passed', models.IntegerField(default=0)),
                ('videos_watched', models.IntegerField(default=0)),
                ('pages_read', models.IntegerField(default=0)),
                ('mood_score', models.FloatField(blank=True, help_text="Score d'humeur/satisfaction", null=True)),
                ('motivation_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrique quotidienne',
                'verbose_name_plural': 'Métriques quotidiennes',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
