# Generated by Django 4.2.8 on 2025-11-21 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_profile', models.JSONField(help_text='Profil utilisateur au moment de la recommandation')),
                ('user_performance', models.JSONField(help_text='Métriques de performance')),
                ('user_emotional_state', models.JSONField(blank=True, help_text='État émotionnel détecté', null=True)),
                ('recommended_items', models.JSONField(help_text='Liste des items recommandés avec scores')),
                ('algorithm_version', models.CharField(max_length=50)),
                ('features_used', models.JSONField(help_text="Features utilisées par l'algorithme")),
                ('user_clicked', models.BooleanField(default=False)),
                ('user_completed', models.BooleanField(default=False)),
                ('user_feedback', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutre'), ('negative', 'Négative')], max_length=20, null=True)),
                ('feedback_score', models.IntegerField(blank=True, help_text='Note (1-5)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de recommandation',
                'verbose_name_plural': 'Journaux de recommandation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty_adjusted', models.CharField(choices=[('same', 'Même difficulté'), ('easier', 'Plus facile'), ('harder', 'Plus difficile')], max_length=20)),
                ('expected_performance', models.FloatField(help_text='Performance attendue (0-100)')),
                ('reason', models.TextField()),
                ('is_attempted', models.BooleanField(default=False)),
                ('is_passed', models.BooleanField(default=False)),
                ('actual_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Recommandation d'exercice",
                'verbose_name_plural': "Recommandations d'exercice",
            },
        ),
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('performance', 'Basé sur la performance'), ('learning_style', "Style d'apprentissage"), ('interests', 'Intérêts'), ('proficiency', 'Niveau de compétence'), ('emotional_state', 'État émotionnel'), ('trend', 'Tendance'), ('similar_users', 'Utilisateurs similaires')], max_length=50)),
                ('reason_explanation', models.TextField(help_text="Explication transparente pour l'utilisateur")),
                ('confidence_score', models.FloatField(help_text='Score de confiance (0-1)')),
                ('priority', models.IntegerField(default=0, help_text="Priorité d'affichage")),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.course')),
                ('recommended_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIExplainability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factors', models.JSONField(help_text='Facteurs influençant la recommandation avec poids')),
                ('primary_factor', models.CharField(max_length=100)),
                ('primary_factor_contribution', models.FloatField(help_text='Contribution du facteur principal (0-1)')),
                ('user_friendly_explanation', models.TextField(help_text='Explication en langage naturel')),
                ('supporting_data', models.JSONField(help_text='Données justifiant la recommandation')),
                ('alternative_recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='recommendations.contentrecommendation')),
            ],
            options={
                'verbose_name': 'Explainability IA',
                'verbose_name_plural': 'Explainability IA',
            },
        ),
        migrations.AddIndex(
            model_name='contentrecommendation',
            index=models.Index(fields=['user', '-created_at'], name='recommendat_user_id_3f1f20_idx'),
        ),
        migrations.AddIndex(
            model_name='contentrecommendation',
            index=models.Index(fields=['confidence_score'], name='recommendat_confide_181326_idx'),
        ),
    ]
