# Generated by Django 5.2.8 on 2025-12-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_course_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('sociology', 'Sociologie'), ('mathematics', 'Mathématiques'), ('science', 'Sciences'), ('history', 'Histoire'), ('literature', 'Littérature'), ('philosophy', 'Philosophie'), ('psychology', 'Psychologie'), ('economics', 'Économie'), ('languages', 'Langues'), ('arts', 'Arts'), ('geography', 'Géographie'), ('computer_science', 'Informatique')], default='sociology', max_length=50, verbose_name='Matière'),
        ),
    ]
