# Generated by Django 5.2.8 on 2025-12-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='custom_youtube_url',
            field=models.URLField(blank=True, help_text='URL YouTube personnalisée pour le cours', null=True),
        ),
    ]
