# Generated by Django 4.2.8 on 2025-11-21 19:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '__first__'),
        ('content', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_emotion', models.CharField(choices=[('happy', 'Heureux'), ('sad', 'Triste'), ('angry', 'En colère'), ('neutral', 'Neutre'), ('surprised', 'Surpris'), ('fearful', 'Apeuré'), ('disgusted', 'Dégoûté'), ('tired', 'Fatigué'), ('focused', 'Concentré'), ('confused', 'Confus')], help_text='Émotion principale détectée', max_length=50)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('emotion_scores', models.JSONField(help_text='Scores pour chaque émotion')),
                ('facial_features', models.JSONField(help_text='Données des traits faciaux détectées')),
                ('activity_context', models.CharField(blank=True, help_text='Activité pendant la détection', max_length=200)),
                ('recommended_action', models.CharField(blank=True, help_text="Action recommandée par l'IA", max_length=200)),
                ('anonymized_image_hash', models.CharField(blank=True, max_length=255)),
                ('is_anonymized', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercise')),
                ('lesson_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Détection d'émotion",
                'verbose_name_plural': "Détections d'émotion",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_accurate', models.BooleanField(help_text='La détection était-elle correcte?')),
                ('actual_emotion', models.CharField(blank=True, choices=[('happy', 'Heureux'), ('sad', 'Triste'), ('angry', 'En colère'), ('neutral', 'Neutre'), ('surprised', 'Surpris'), ('fearful', 'Apeuré'), ('disgusted', 'Dégoûté'), ('tired', 'Fatigué'), ('focused', 'Concentré'), ('confused', 'Confus')], max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotion_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions.emotiondetection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Feedback d'émotion",
                'verbose_name_plural': "Feedbacks d'émotion",
            },
        ),
        migrations.CreateModel(
            name='EmotionalTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('dominant_emotion', models.CharField(choices=[('happy', 'Heureux'), ('sad', 'Triste'), ('angry', 'En colère'), ('neutral', 'Neutre'), ('surprised', 'Surpris'), ('fearful', 'Apeuré'), ('disgusted', 'Dégoûté'), ('tired', 'Fatigué'), ('focused', 'Concentré'), ('confused', 'Confus')], max_length=50)),
                ('emotion_distribution', models.JSONField(help_text='Distribution des émotions par jour')),
                ('correlation_with_performance', models.FloatField(blank=True, null=True)),
                ('correlation_with_activities', models.JSONField(default=dict)),
                ('insights', models.TextField(blank=True)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tendance émotionnelle',
                'verbose_name_plural': 'Tendances émotionnelles',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_emotion', models.CharField(choices=[('happy', 'Heureux'), ('sad', 'Triste'), ('angry', 'En colère'), ('neutral', 'Neutre'), ('surprised', 'Surpris'), ('fearful', 'Apeuré'), ('disgusted', 'Dégoûté'), ('tired', 'Fatigué'), ('focused', 'Concentré'), ('confused', 'Confus')], max_length=50)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('mood_trend', models.CharField(choices=[('improving', 'Amélioration'), ('declining', 'Détérioration'), ('stable', 'Stable')], max_length=20)),
                ('stress_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('engagement_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('fatigue_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('needs_break', models.BooleanField(default=False)),
                ('recommended_break_duration', models.IntegerField(blank=True, help_text='Durée recommandée en minutes', null=True)),
                ('needs_support', models.BooleanField(default=False)),
                ('support_type', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'État émotionnel',
                'verbose_name_plural': 'États émotionnels',
            },
        ),
        migrations.CreateModel(
            name='EmotionAdaptation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adaptation_type', models.CharField(choices=[('break', 'Pause recommandée'), ('difficulty_adjust', 'Ajustement de difficulté'), ('change_content_type', 'Changement de type de contenu'), ('motivation_message', 'Message de motivation'), ('slower_pace', 'Rythme plus lent'), ('faster_pace', 'Rythme plus rapide'), ('support_resources', 'Ressources de support')], max_length=50)),
                ('description', models.TextField()),
                ('message_to_user', models.TextField()),
                ('new_difficulty', models.CharField(blank=True, choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], max_length=20)),
                ('new_content_type', models.CharField(blank=True, max_length=50)),
                ('recommended_resource', models.CharField(blank=True, max_length=500)),
                ('user_accepted', models.BooleanField(blank=True, null=True)),
                ('effectiveness', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotion_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotions.emotiondetection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_adaptations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adaptation émotionnelle',
                'verbose_name_plural': 'Adaptations émotionnelles',
            },
        ),
        migrations.AddIndex(
            model_name='emotiondetection',
            index=models.Index(fields=['user', '-created_at'], name='emotions_em_user_id_16fd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='emotiondetection',
            index=models.Index(fields=['detected_emotion'], name='emotions_em_detecte_b7353d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emotionaltrend',
            unique_together={('user', 'date')},
        ),
    ]
