# Generated by Django 4.2.8 on 2025-11-21 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('summary', models.CharField(max_length=500)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('instructor', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='courses/')),
                ('video_intro', models.URLField(blank=True)),
                ('duration_hours', models.FloatField(help_text='Durée estimée en heures')),
                ('prerequisites', models.JSONField(default=list, help_text='IDs des cours préalables')),
                ('learning_outcomes', models.JSONField(default=list)),
                ('students_enrolled', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Texte'), ('video', 'Vidéo'), ('article', 'Article'), ('interactive', 'Interactif'), ('document', 'Document')], max_length=20)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('text_content', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('video_duration', models.IntegerField(blank=True, help_text='Durée vidéo en secondes', null=True)),
                ('document_file', models.FileField(blank=True, upload_to='lessons/documents/')),
                ('external_url', models.URLField(blank=True)),
                ('learning_objectives', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('link', 'Lien'), ('tool', 'Outil'), ('reference', 'Référence')], max_length=50)),
                ('file', models.FileField(blank=True, upload_to='resources/')),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='content.lesson')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('is_locked', models.BooleanField(default=False)),
                ('unlock_condition', models.CharField(blank=True, help_text='Condition pour débloquer', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.module'),
        ),
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='content.course')),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cours inscrit',
                'verbose_name_plural': 'Cours inscrits',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', '-published_at'], name='content_cou_status_79a980_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='content_cou_categor_1460b4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['difficulty_level'], name='content_cou_difficu_10ed71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AddIndex(
            model_name='enrolledcourse',
            index=models.Index(fields=['user', '-enrolled_at'], name='content_enr_user_id_ecd615_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolledcourse',
            index=models.Index(fields=['course'], name='content_enr_course__d0984b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together={('user', 'course')},
        ),
    ]
