# Generated by Django 5.2.8 on 2025-12-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='school_level',
            field=models.CharField(choices=[('primary', 'Primaire'), ('secondary', 'Secondaire'), ('university', 'Université'), ('professional', 'Formation professionnelle')], default='secondary', max_length=50, verbose_name='Niveau scolaire'),
        ),
    ]
